# Taken from Hyprland repo
name: "Setup base"

inputs:
  INSTALL_XORG_PKGS:
    description: 'Install xorg dependencies'
    required: false
    default: false
  branch:
    description: 'Hyprland branch to checkout'
    required: false
    default: 'main'
  hyprwayland:
    description: 'Hyprwayland branch to checkout'
    required: false
    default: 'main'

runs:
  using: "composite"
  steps:
    - name: Install Hyprland and dependencies
      shell: bash
      run: |
        sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
        pacman --noconfirm --noprogressbar -Syyu
        pacman --noconfirm --noprogressbar -Sy \
          base-devel \
          cairo \
          clang \
          cmake \
          git \
          glaze \
          glm \
          glslang \
          go \
          hyprland \
          jq \
          libc++ \
          libdisplay-info \
          libdrm \
          libepoxy \
          libfontenc \
          libglvnd \
          libinput \
          libjxl \
          libliftoff \
          libspng \
          libwebp \
          libxcursor \
          libxcvt \
          libxfont2 \
          libxkbcommon \
          libxkbfile \
          lld \
          meson \
          ninja \
          pango \
          pixman \
          pkgconf \
          pugixml \
          scdoc \
          seatd \
          systemd \
          tomlplusplus \
          wayland \
          wayland-protocols \
          xcb-util-errors \
          xcb-util-renderutil \
          xcb-util-wm \
          xcb-util \
          xcb-util-image \
          libzip \
          librsvg \
          re2

    - name: Get Xorg pacman pkgs
      shell: bash
      if: inputs.INSTALL_XORG_PKGS == 'true'
      run: |
        pacman --noconfirm --noprogressbar -Sy \
          xorg-fonts-encodings \
          xorg-server-common \
          xorg-setxkbmap \
          xorg-xkbcomp \
          xorg-xwayland

    # Fix an issue with actions/checkout where the checkout repo is not mark as safe
    - name: Mark directory as safe for git
      shell: bash
      run: |
        git config --global --add safe.directory /__w/hyprland-virtual-desktops/hyprland-virtual-desktops