name: Build hyprland-virtual-desktops

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  gcc_main:
    name: "Build hyprland-virtual-desktops (main)"
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Checkout repository action
        uses: actions/checkout@v4

      - name: Setup base on main
        uses: ./.github/actions/setup_base
        with:
          INSTALL_XORG_PKGS: true

      - name: Build hyprland-virtual-desktops
        env:
          PKG_CONFIG_PATH: "/usr/local/share/pkgconfig/"
        run: |
          make all