name: Build hyprland-virtual-desktops

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  gcc_main:
    name: "Build hyprland-virtual-desktops (main)"
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Checkout repository action
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup base environment
        uses: ./.github/actions/setup_base
        with:
          INSTALL_XORG_PKGS: true
          branch: ${{ (github.ref == 'refs/heads/dev' || github.base_ref == 'dev') && 'main' || 'v0.49.0' }}
          hyprwayland: ${{ (github.ref == 'refs/heads/main' || github.base_ref == 'main') && 'v0.4.2' || '' }}

      - name: Compile Hyprland
        shell: bash
        run: |
          cd Hyprland
          make all
          make install

      - name: Build hyprland-virtual-desktops
        env:
          PKG_CONFIG_PATH: "/usr/local/share/pkgconfig/"
        run: |
          make all
